N = int(input('Digite um numero:'))
print('\033[35m='*20)
print('   \033[1;31mTABUADA DE {}\033[m'.format(N))
print('\033[35m='*20)

print('{}x1={}'.format(N, N))
print('{}x2={}'.format(N, N*2))
print('{}x3={}'.format(N, N*3))
print('{}x4={}'.format(N, N*4))
print('{}x5={}'.format(N, N*5))
print('{}x6={}'.format(N, N*6))
print('{}x7={}'.format(N, N*7))
print('{}x8={}'.format(N, N*8))
print('{}x9={}'.format(N, N*9))
print('{}x10={}'.format(N, N*10))
